# Generated by Django 5.0.4 on 2024-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_candidat_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disciplines/'),
        ),
    ]
