# Generated by Django 5.0.4 on 2024-06-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_vote_amount_vote_transaction_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='transaction_reference',
        ),
    ]
