# Generated by Django 5.0.4 on 2024-06-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_vote_amount_remove_vote_transaction_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
