# Generated by Django 5.0.4 on 2024-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_candidat_options_remove_candidat_identifier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'ordering': ['identifier']},
        ),
        migrations.AddField(
            model_name='candidat',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
