# Generated by Django 5.0.4 on 2024-06-12 21:22

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_candidat_options_candidat_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='transaction_reference',
            field=models.CharField(default=listings.models.generate_transaction_reference, max_length=20),
        ),
    ]
